name: GitHub Readme YouTube Cards
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCOHQVDImUQloRIwrOBewfCQ

